name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 3h UTC
  workflow_dispatch:      # Permite executar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/d60/twikit
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
